### ISSUE TITLE
Unrecognized type []interface {} for item

### ISSUE THREAD

**Issue by gphelps101** [graphite-ng/carbon-relay-ng#226]
Recieving: ▶ ERRO  Unrecognized type []interface {} in the logs for relay-ng
with the latest version:
carbon-relay-ng, 0.9.2-5-g37e9ca8-1

Seeing this issue when the carbon-relays get turned on and send to the carbon-cache (seeing this in the carbon-cache only).

```
instance = "ip-10-8-2-39"

max_procs = 16

listen_addr = "0.0.0.0:2003"
pickle_addr = "0.0.0.0:2004"
admin_addr  = "0.0.0.0:2013"
http_addr   = "0.0.0.0:8081"
spool_dir   = "/mnt/spool"
pid_file    = "carbon-relay-ng.pid"
log_level   = "notice"
bad_metrics_max_age     = "1h"
validation_level_legacy = "strict"
validation_level_m20    = "medium"
validate_order          = true

[init]
cmds = [
  'addRoute consistentHashing Primary  127.0.0.1:2024:a spool=true pickle=true  127.0.0.1:2034:b spool=true pickle=true  127.0.0.1:2044:c spool=true pickle=true',
  'addRoute consistentHashing Secondary  127.0.0.1:2054:d spool=true pickle=true  127.0.0.1:2064:e spool=true pickle=true  127.0.0.1:2074:f spool=true pickle=true',
]

[instrumentation]
graphite_addr = "graphite-relay-pr.svc.aws-usw02.ice.gecis.io:2003"
graphite_interval = 1000 # in ms
```

The above is my carbon-relay-ng.conf file in my carbon-cache.  Using version 0.8.8-1 works (without the new [init], cmds syntax).  Can anyone assist explain?

Thanks!

**Comment by Dieterbe** [comment]
are you 100% sure this is the config file that it's reading? it doesn't look like it. i just started 0.9.2-5-g37e9ca8 with your config and it starts fine

**Comment by gphelps101** [comment]
It will start fine standlone, I'm currently running chef-dk locally and the config works.  I have 6 front end carbon-relays with a similar config:
addRoute consistentHashing Primary <ip> <cache> spool=true pickle=true 
addRoute consistentHashing Secondary <ip> <cache> spool=true pickle=true 

The problem exists on the carbon-caches with the pickle=true configuration.  

Any other ideas on why it would it fail?

**Comment by Dieterbe** [comment]
i'm confused. you're saying carbon-relay-ng logs this, after startup, during operation, when it's configured to send pickled data to a remote carbon server? does it log anything else?

**Comment by gphelps101** [comment]
After I begin sending data from the relay-ng layer to the relay-ng cache layer once I send pickled data from the relay to cache I see:
"Unrecognized type []interface {} for item" using the 0.9.2 version

**Comment by randallt** [comment]
I am also seeing this in the carbon-relay-ng logs (version carbon-relay-ng-0.9.3_7_gfe37e8f-1.x86_64) when trying to relay pickled data from another instance of carbon-relay-ng. When I set pickled=false and used the line protocol port (in the sending config), it stopped. I have also had problems with a 3rd-party receiver (wavefront proxy) parsing the pickled data from carbon-relay-ng properly. Something isn't right.

**Comment by randallt** [comment]
+1

**Comment by Dieterbe** [comment]
Hi folks, sorry it took so long, but I just merged #341 which fixes this.
You can now have a carbon-relay-ng send pickled data to another carbon-relay-ng.

I don't understand why anyone would want to do this, as the pickle protocol uses more bandwith, is generally unpleasant to work with, and is a pain to troubleshoot (trying sniffing pickled data off the network...).  I would definitely advise to just use the text protocol.
But anyway, you can now...

**Comment by Dieterbe** [comment]
@gphelps101 @randallt @ralphM78 can you try out the latest version and let me know how it goes?

**Comment by ralphM78** [comment]
@Dieterbe Thanks for implementing this feature. I have set pickle=true with the new version and it works. A little bit more bandwith usage but not that heavy. So it works, but doesn't solve my problem with dropped packages. It isn't an improvment against plain text, but who wants to use this, can do it now.

**Comment by Dieterbe** [comment]
> but doesn't solve my problem with dropped packages.

is there a different ticket for this?

**Comment by ralphM78** [comment]
@Dieterbe no. I'm actually not really sure if it's OS or carbon-relay-ng related. I have set net.core.rmem_max and net.core.rmem_default to high values but there are between 300 and 1000 dropped packages per second in /proc/net/udp for carbon-relay-ng. On the same host a central collectd is running which sends the metrics to the local carbon-relay-ng. If I setup carbon-relay-ng on a smaller host without running collectd on it, I don't see dropped packages. I'm a little bit confused.

**Comment by Dieterbe** [comment]
is it an option to use TCP instead?

**Comment by ralphM78** [comment]
Using TCP caused a strange behaivior. collectd has consumed all the memory until OOM. But I think I have found the reason for that. After replacing a regex inside blacklist config with sub , collectd doesn't consume all the memory and can send all metrics. Maybe the regex has slowed down carbon-relay-ng that much and collectd wasn't able to send all metrics fast enough.

**Comment by Dieterbe** [comment]
Maybe, yes. Go's regex library is slow and sensitive to unoptimized expressions. You could tell if at least a cpu core was maxed out by the relay.
